### ISSUE TITLE
Issue with the Data type

### ISSUE THREAD

**Issue by CodingTheUnknown** [programmingwithswift/ReadJSONFileURL#1]
The issue as seen in the photo below is that the type Data cant return the type Data?

![image](https://user-images.githubusercontent.com/10836951/93802492-725a1e00-fc3b-11ea-821a-d9a54dcf0af1.png)

**Comment by programmingwithswift** [comment]
Sorry I took so long. None of this is from my code so I cannot properly comment on it. One thing I notice is that you have created a class called Data. This is built in, try and rename the class.

I hope this help. 

In the future, before opening an issue(provided it is a code issue), please ensure that the issue is with the code that is in the project files I have provided. If there is no issue in the code I have provided then the issue is most likely in your code and stack overflow might be a better(quicker to respond than me) place to ask the question.
